[project]
name = "mospolytech-schedule-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Krasnov Rodion Denisovic", email = "rodion.dict@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "django-environ>=0.14.0",
    "django-extensions>=4.1",
    "djangorestframework>=3.18.1",
    "drf-spectacular>=0.30.0",
    "ortools",
    "psycopg2-binary>=2.9.13",
]

[project.scripts]
mospolytech-schedule-backend = "mospolytech_schedule_backend:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
