# Generated by Django 6.1.1 on 2026-10-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'корпус',
                'verbose_name_plural': 'корпуса',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('format', models.CharField(choices=[('OFFLINE', 'Очно'), ('ONLINE', 'Онлайн'), ('ANY', 'Любой')], default='OFFLINE', max_length=10, verbose_name='формат')),
                ('multi_group', models.BooleanField(default=False, help_text='True — занятие ведётся сразу для набора групп (лекции).', verbose_name='несколько групп')),
                ('generate', models.BooleanField(default=True, help_text='False — расписание не строится (физкультура).', verbose_name='участвует в генерации')),
                ('project_based', models.BooleanField(default=False, help_text='True — участники определяются выбором проекта, а не академической группой.', verbose_name='группа по проекту (ПД)')),
            ],
            options={
                'verbose_name': 'вид занятия',
                'verbose_name_plural': 'виды занятий',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'кафедра',
                'verbose_name_plural': 'кафедры',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('capacity', models.PositiveSmallIntegerField(default=0, help_text='0 — без ограничения.', verbose_name='максимум участников')),
            ],
            options={
                'verbose_name': 'проект (ПД)',
                'verbose_name_plural': 'проекты (ПД)',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год начала')),
                ('number', models.PositiveSmallIntegerField(help_text='1 — первый (осенний), 2 — второй (весенний)', verbose_name='номер семестра')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='начало')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='конец')),
            ],
            options={
                'verbose_name': 'семестр',
                'verbose_name_plural': 'семестры',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'дисциплина',
                'verbose_name_plural': 'дисциплины',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeekPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'шаблон недель',
                'verbose_name_plural': 'шаблоны недель',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('course', models.PositiveSmallIntegerField(help_text='Номер курса. 1 — первокурсник (важно для правил ПД).', verbose_name='курс')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='mospolytech_schedule_backend.department', verbose_name='кафедра')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('number', models.CharField(max_length=20, verbose_name='номер')),
                ('capacity', models.PositiveSmallIntegerField(default=0, verbose_name='вместимость')),
                ('online_url', models.URLField(blank=True, help_text='Заполняется для онлайн-занятий вместо физической комнаты.', verbose_name='онлайн-ссылка')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='mospolytech_schedule_backend.building', verbose_name='корпус')),
            ],
            options={
                'verbose_name': 'помещение',
                'verbose_name_plural': 'помещения',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='mospolytech_schedule_backend.group', verbose_name='учебная группа')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенты',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='mospolytech_schedule_backend.project', verbose_name='проект')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_groups', to='mospolytech_schedule_backend.semester', verbose_name='семестр')),
                ('members', models.ManyToManyField(blank=True, related_name='project_groups', to='mospolytech_schedule_backend.student', verbose_name='участники')),
            ],
            options={
                'verbose_name': 'ПД-группа',
                'verbose_name_plural': 'ПД-группы',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='mospolytech_schedule_backend.project', verbose_name='проект')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_choices', to='mospolytech_schedule_backend.semester', verbose_name='семестр')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_choices', to='mospolytech_schedule_backend.student', verbose_name='студент')),
            ],
            options={
                'verbose_name': 'выбор проекта',
                'verbose_name_plural': 'выборы проектов',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='отчество')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='mospolytech_schedule_backend.department', verbose_name='кафедра')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='mospolytech_schedule_backend.teacher', verbose_name='руководитель'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('number', models.PositiveSmallIntegerField(verbose_name='номер пары')),
                ('start_time', models.TimeField(verbose_name='начало')),
                ('end_time', models.TimeField(verbose_name='конец')),
            ],
            options={
                'verbose_name': 'временной слот',
                'verbose_name_plural': 'временные слоты',
                'ordering': ('start_time',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('number',), name='uniq_timeslot_number')],
            },
        ),
        migrations.CreateModel(
            name='EventSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, help_text='0=понедельник … 6=воскресенье. None — время не закреплено (физра).', null=True, verbose_name='день недели')),
                ('online_url', models.URLField(blank=True, help_text='Для занятий в формате ONLINE.', verbose_name='онлайн-ссылка')),
                ('is_generated', models.BooleanField(default=False, help_text='False — слот-заготовка либо занятие вне генерации (физра).', verbose_name='сгенерировано')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='mospolytech_schedule_backend.classtype', verbose_name='вид занятия')),
                ('groups', models.ManyToManyField(blank=True, related_name='events', to='mospolytech_schedule_backend.group', verbose_name='учебные группы')),
                ('project_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='mospolytech_schedule_backend.projectgroup', verbose_name='ПД-группа')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='mospolytech_schedule_backend.room', verbose_name='помещение')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='mospolytech_schedule_backend.semester', verbose_name='семестр')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='mospolytech_schedule_backend.subject', verbose_name='дисциплина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='mospolytech_schedule_backend.teacher', verbose_name='преподаватель')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='mospolytech_schedule_backend.timeslot', verbose_name='временной слот')),
                ('week_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='mospolytech_schedule_backend.weekpattern', verbose_name='шаблон недель')),
            ],
            options={
                'verbose_name': 'пара в расписании',
                'verbose_name_plural': 'расписание (пары)',
                'ordering': ('weekday', 'time_slot__start_time', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='uniq_room_in_building'),
        ),
        migrations.AddConstraint(
            model_name='projectgroup',
            constraint=models.UniqueConstraint(fields=('project', 'semester'), name='uniq_project_group_per_semester'),
        ),
        migrations.AddConstraint(
            model_name='projectchoice',
            constraint=models.UniqueConstraint(fields=('student', 'semester'), name='uniq_project_choice_per_semester'),
        ),
    ]
