# Generated by Django 5.2.17 on 2026-10-04 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидание'), ('SOLVED', 'Решено'), ('PARTIAL', 'Частично'), ('INFEASIBLE', 'Неразрешимо'), ('ERROR', 'Ошибка')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('objective_value', models.IntegerField(blank=True, null=True, verbose_name='Значение целевой функции')),
                ('solve_time_seconds', models.FloatField(blank=True, null=True, verbose_name='Время решения (сек)')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Запуск генерации',
                'verbose_name_plural': 'Запуски генерации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('is_first_year_first_semester', models.BooleanField(default=False, help_text='Такие группы не участвуют в проектной деятельности.', verbose_name='Перваки, первый семестр')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('max_students', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Макс. студентов')),
            ],
            options={
                'verbose_name': 'Проект (ПД)',
                'verbose_name_plural': 'Проекты (ПД)',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('capacity', models.PositiveSmallIntegerField(default=30, verbose_name='Вместимость')),
                ('allows_lecture', models.BooleanField(default=True, verbose_name='Подходит для лекций')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('weeks_count', models.PositiveSmallIntegerField(default=18, verbose_name='Недель')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестры',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('max_pairs_per_day', models.PositiveSmallIntegerField(default=4, verbose_name='Макс. пар в день')),
                ('max_pairs_per_week', models.PositiveSmallIntegerField(default=20, verbose_name='Макс. пар в неделю')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='LectureStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(related_name='lecture_streams', to='schedule_generator.group', verbose_name='Группы')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='schedule_generator.semester', verbose_name='Семестр')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='schedule_generator.subject', verbose_name='Дисциплина')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streams', to='schedule_generator.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Лекционный поток',
                'verbose_name_plural': 'Лекционные потоки',
            },
        ),
        migrations.CreateModel(
            name='LessonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('PRACTICE', 'Практика'), ('LAB', 'Лабораторная'), ('LECTURE', 'Лекция'), ('PE', 'Физкультура'), ('PD', 'Проектная деятельность'), ('EXTRACURRICULAR', 'Внеучебная деятельность')], max_length=20, verbose_name='Тип занятия')),
                ('format', models.CharField(blank=True, choices=[('ONSITE', 'Очно'), ('ONLINE', 'Онлайн')], help_text='Заполняется только для внеучебки; остальные типы имеют фиксированный формат.', max_length=10, null=True, verbose_name='Формат')),
                ('pairs_per_week', models.PositiveSmallIntegerField(default=1, verbose_name='Пар в неделю')),
                ('audience_size', models.PositiveSmallIntegerField(default=25, verbose_name='Слушателей')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedule_generator.group', verbose_name='Группа')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedule_generator.lecturestream', verbose_name='Лекционный поток')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedule_generator.project', verbose_name='Проект (ПД)')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedule_generator.semester', verbose_name='Семестр')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedule_generator.subject', verbose_name='Дисциплина')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='schedule_generator.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Занятие (план)',
                'verbose_name_plural': 'Занятия (план)',
            },
        ),
        migrations.CreateModel(
            name='GenerationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('WARNING', 'Предупреждение'), ('ERROR', 'Ошибка')], default='WARNING', max_length=10, verbose_name='Уровень')),
                ('text', models.TextField(verbose_name='Текст')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='schedule_generator.generationrun')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule_generator.lessonevent')),
            ],
            options={
                'verbose_name': 'Проблема генерации',
                'verbose_name_plural': 'Проблемы генерации',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='schedule_generator.semester', verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='group',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schedule_generator.semester', verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='schedule_generator.semester', verbose_name='Семестр'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schedule_generator.group', verbose_name='Учебная группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='ProjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schedule_generator.project', verbose_name='Проект')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_choice', to='schedule_generator.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Выбор проекта',
                'verbose_name_plural': 'Выборы проектов',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='schedule_generator.teacher', verbose_name='Руководитель'),
        ),
        migrations.CreateModel(
            name='WeekPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Базовая неделя', max_length=50, verbose_name='Название')),
                ('parity', models.PositiveSmallIntegerField(choices=[(0, 'Любая'), (1, 'Нечётная'), (2, 'Чётная')], default=0, verbose_name='Чётность недели')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_patterns', to='schedule_generator.semester')),
            ],
            options={
                'verbose_name': 'Шаблон недели',
                'verbose_name_plural': 'Шаблоны недель',
                'unique_together': {('semester', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота')], verbose_name='День недели')),
                ('lesson_number', models.PositiveSmallIntegerField(verbose_name='Номер пары')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Конец')),
                ('week_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedule_generator.weekpattern')),
            ],
            options={
                'verbose_name': 'Слот (пара)',
                'verbose_name_plural': 'Слоты (пары)',
                'ordering': ['day_of_week', 'lesson_number'],
                'unique_together': {('week_pattern', 'day_of_week', 'lesson_number')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schedule_generator.lessonevent', verbose_name='Занятие')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='schedule_generator.room', verbose_name='Аудитория')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='schedule_generator.generationrun', verbose_name='Запуск')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schedule_generator.timeslot', verbose_name='Слот')),
            ],
            options={
                'verbose_name': 'Пара в расписании',
                'verbose_name_plural': 'Пары в расписании',
                'constraints': [models.UniqueConstraint(fields=('event', 'slot'), name='uniq_event_slot')],
            },
        ),
    ]
